version: '3.8'
services:
  step_up_web:
    build:
      # context: .
      dockerfile: Dockerfile
    image: step_up_web   
    container_name: step_up_web
    restart: unless-stopped 
    ports:
      - "8000:8000" 
    deploy:
      resources:
        limits:
          cpus: '0.6' 

  nginx_react:
    image: nginx:alpine
    ports:
      - "169:169"
    restart: unless-stopped 
    # volumes:
    #   - ./nginx/conf.d/default_react.conf:/etc/nginx/conf.d/default_react.conf 
    depends_on:
      - step_up_web  
networks:
  react:
    driver: bridge
volumes:
  node_modules:


