version: '3.8'
services:
  step_up_web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - API_HOST=http://step-up-kh.duckdns.org:168
    image: step_up_web   
    container_name: step_up_web
    restart: unless-stopped 
    ports:
      - "8000:8000"
    working_dir: /usr/share/nginx/html
    deploy:
      resources:
        limits:
          cpus: '0.6'

  nginx_react:
    image: nginx:alpine
    ports:
      - "169:169"
    volumes:
      - ./nginx/conf.d/default_react.conf:/etc/nginx/conf.d/default_react.conf 
    depends_on:
      - step_up_web  
networks:
  react:
    driver: bridge
