version: '3.8'
services:
  step_up_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - react
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          cpus: '0.6'
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile_node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - react
  nginx:
    image: nginx:latest
    ports:
      - "169:169"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - step_up_web
      - nodejs
  duckdns_react:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=step-up-kh.duckdns.org
      - TOKEN=2fa0c36d-66a5-4242-acfa-d1cfcd1227c3
      - LOG_FILE=true
    restart: unless-stopped
networks:
  react:
    driver: bridge
