# docker-compose.yml
version: '3.8'
services:
  step_up_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '169:169'
    depends_on:
      - step_up_app
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '0.6'
networks:
  laravel:
    external: true