# docker-compose.yml
version: '3.8'
services:
  step_up_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '169:169'
    networks:
      - react
    volumes:
      - ./app:/app
    # environment:
      # - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.6'
networks:
  react:
    driver: bridge